### ISSUE TITLE
多文件词典读取错误

### ISSUE THREAD

**Issue by WingGao** [terasum/js-mdict#3]
```
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: key_block_info length should equal
    at Mdict._decodeKeyBlockInfo (/Users/x/Projs/youdao_wordbook_tool/node_modules/js-mdict/lib/MdictBase.js:391:28)
    at Mdict._readKeyBlockInfo (/Users/x/Projs/youdao_wordbook_tool/node_modules/js-mdict/lib/MdictBase.js:354:35)
    at Mdict.MDictBase (/Users/x/Projs/youdao_wordbook_tool/node_modules/js-mdict/lib/MdictBase.js:114:10)
    at new Mdict (/Users/x/Projs/youdao_wordbook_tool/node_modules/js-mdict/lib/Mdict.js:54:95)
```
用的是这本词典https://www.pdawiki.com/forum/thread-35803-1-1.html

**Comment by songxiaocheng** [comment]
似乎不是多文件的问题，而是词典版本小于 2.0 的问题。我手头的 2.0 版本的词典没问题，1.x 版本的都有问题。

断言失败是因为 `this.keyHeader.keyBlockInfoDecompSize` 为0，而查看了下代码，只有版本在2.0以上的情况下才设置了该属性，版本小于2.0时该属性就保持初始值0了，如下所示：
https://github.com/terasum/js-mdict/blob/a3f75312071d0433ff808f994ce4f7fbf292ad03/src/mdict-base.js#L287-L293

另外，似乎不止这处，其余多处断言也会在版本 1.x 的情况下失败。

我对mdict格式不了解，因此对修复无能为力，希望该库能够早日支持 1.x 版本的词典。

**Comment by terasum** [comment]
@songxiaocheng 你好，可以帮忙提供一个 1.0 版本的 mdx 词典吗，我手边目前都是2.0以上的，我也没有遇到过1.0的词库，所以我本地无法复现你说的问题。

**Comment by songxiaocheng** [comment]
您好，https://github.com/terasum/js-mdict/issues/3 中我提到的有问题的词典都是1.2版本的（是用该库输出的版本号）。

不过我刚刚又发现一个问题：有部分 2.0 版本的词典 this._encrypt 为 0，导致 kbInfoCompBuff 为 undefined 导致后续调用 slice 时候报错：TypeError: Cannot read property 'slice' of undefined。代码段为：
https://github.com/terasum/js-mdict/blob/a3f75312071d0433ff808f994ce4f7fbf292ad03/src/mdict-base.js#L357-L366

我把上述有问题的词典都放在百度云里了，分别放入 “词典v1.2” 和 “词典v2.0” 两个文件夹：
链接: https://pan.baidu.com/s/174J9Lz94Klakx0RI5UzFzw 提取码: muwr
此链接一个月有效。

另外，上述词典，我刚测试可在python版的 https://github.com/ninja33/mdx-server 中正常读取，您可能知道，其中的 readmdict.py 是解析词典文件的，可供参考。

谢谢！


On Jun 21, 2021, at 19:44, Chen Quan ***@***.******@***.***>> wrote:



@songxiaocheng<https://github.com/songxiaocheng> 你好，可以帮忙提供一个 1.0 版本的 mdx 词典吗，我手边目前都是2.0以上的，我也没有遇到过1.0的词库，所以我本地无法复现你说的问题。

**Comment by songxiaocheng** [comment]
@terasum 已经邮件私信发送到您的公开邮箱。

**Comment by iibrat** [comment]
请问一下，多文件词典是如何初始化的？？
我导入牛津词典，它有很几个文件。
![image](https://github.com/user-attachments/assets/1b47ad49-1be5-4509-bb34-8121b6915492)
我看这个构造函数是不是只能传入一个文件路径？？

**Comment by terasum** [comment]
version v6.0.3 fixed this.
